# SPDX-FileCopyrightText: 2026 John Romkey
#
# SPDX-License-Identifier: MIT

name: GitHub Release Actions

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Build and upload CircuitPython release assets
        uses: ./.github/actions/circuitpython-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upload-url: ${{ github.event.release.upload_url }}
